events{
    worker_connections 1024;
}
http{
    upstream goredis_backend{
        server goredis:8080;
    }

    server{
        listen 80;

        server_name goredis.me;

        location / {
            proxy_pass http://goredis_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }
    }

}